In [1]:
import numpy as pd
import pandas as pd

In [3]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [4]:
  date.describe()

        product_id      city_id       orders
count  1000.000000  1000.000000  1000.000000
mean   3826.379000    16.371000    17.497000
std    2217.585914     8.554211    57.357841
min       5.000000     0.000000     1.000000
25%    1935.000000    13.000000     1.000000
50%    3810.000000    16.000000     4.000000
75%    5778.000000    25.000000    12.000000
max    7585.000000    30.000000  1004.000000

In [5]:
time.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [8]:
date['date']=pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [14]:
#Extract year
date['date_year']=date['date'].dt.year

In [15]:
date.sample(5)

          date  product_id  city_id  orders  date_year
246 2019-12-10        2253       13      46       2019
459 2019-05-02        3803       21       2       2019
76  2019-04-18        5973       16       1       2019
820 2019-07-27        7239       22       2       2019
113 2018-12-15        6288        2       2       2018

In [19]:
#Extract months
date['date_months']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_months
74  2019-11-13        2199       14       2       2019           11
441 2019-02-15        2906       16       2       2019            2
787 2019-07-19        5371       22       8       2019            7
38  2019-02-15        7025       14      33       2019            2
321 2019-12-04        2981       26     461       2019           12

In [21]:
#Extract days
date['date_days']=date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  date_year  date_months  date_days
663 2018-11-19        3761       16       1       2018           11         19
194 2019-08-09           5       16       1       2019            8          9
693 2019-07-26        2271        3      60       2019            7         26
315 2018-11-10        3345       13      23       2018           11         10
31  2018-10-01        7386        3       1       2018           10          1

In [23]:

# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_months,date_days,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [24]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_months  date_days  date_dow date_dow_name
0 2019-12-10       2019           12         10         1       Tuesday
1 2018-08-15       2018            8         15         2     Wednesday
2 2018-10-23       2018           10         23         1       Tuesday
3 2019-08-17       2019            8         17         5      Saturday
4 2019-01-06       2019            1          6         6        Sunday

In [27]:

import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 10, 7, 12, 3, 13, 76735)

In [28]:

today - date['date']

0     2493 days 12:03:13.076735
1     2975 days 12:03:13.076735
2     2906 days 12:03:13.076735
3     2608 days 12:03:13.076735
4     2831 days 12:03:13.076735
                 ...
995   2921 days 12:03:13.076735
996   2862 days 12:03:13.076735
997   2710 days 12:03:13.076735
998   2775 days 12:03:13.076735
999   2549 days 12:03:13.076735
Name: date, Length: 1000, dtype: timedelta64[ns]